resolver: lts-9.17
extra-deps:
  - distributed-process-0.6.6
  - distributed-process-client-server-0.2.3
  - distributed-process-extras-0.3.2
  - network-transport-0.4.4.0
  - network-transport-tcp-0.5.1
  - distributed-process-async-0.2.4.1
  - distributed-process-simplelocalnet-0.2.3.3
  - syb-0.6
packages:
- .
